## 1 задача
Скачать данные по ссылке https://www.kaggle.com/datasets/shivachandel/kc-house-data
Считать данные с помощью pandas
Вывести на экран первые 5 строк
Посмотреть на описание признаков и на их содержание

In [19]:
import pandas as pd
df = pd.read_csv(r'kc_house_data.csv')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7      1180.0              0   
1      7242     2.0           0     0  ...      7      2170.0            400   
2     10000     1.0           0     0  ...      6       770.0              0   
3      5000     1.0           0     0  ...      7      1050.0            910   
4      8080     1.0           0     0  ...      8      1680.0              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21611 non-null  float64
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

## 2 задача
Проведите первичный анализ данных
Изучите типы данных
Найдите количество пропущенных ячеек в данных
Посчитайте основные статистики по всем признакам и поизучайте их
Пишите выводы

In [21]:
df.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  21613.000000  21613.000000  21613.000000   
mean   4.580302e+09  5.400881e+05      3.370842      2.114757   2079.899736   
std    2.876566e+09  3.671272e+05      0.930062      0.770163    918.440897   
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000   
25%    2.123049e+09  3.219500e+05      3.000000      1.750000   1427.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      0.234303      3.409430   
std    4.142051e+04      0.539989      0.086517      0.766318      0.650743   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068800e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

              grade    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  21613.000000  21611.000000   21613.000000  21613.000000  21613.000000   
mean       7.656873   1788.396095     291.509045   1971.005136     84.402258   
std        1.175459    828.128162     442.575043     29.373411    401.679240   
min        1.000000    290.000000       0.000000   1900.000000      0.000000   
25%        7.000000   1190.000000       0.000000   1951.000000      0.000000   
50%        7.000000   1560.000000       0.000000   1975.000000      0.000000   
75%        8.000000   2210.000000     560.000000   1997.000000      0.000000   
max       13.000000   9410.000000    4820.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000  
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652  
std       53.505026      0.138564      0.140828     685.391304   27304.179631  
min    98001.000000     47.155900   -122.519000     399.000000     651.000000  
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000  
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000  
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000  
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

In [26]:
df.describe(include=['object'])

date
count             21613
unique              372
top     20140623T000000
freq                142

В столбце sqft_above пропушено два значения. 


## 3 задача
Ответьте на несколько вопросов
### 3.1 
В каком диапазоне изменяются стоимости недвижимости?


In [23]:
df['price'].min()

75000.0

In [24]:
df['price'].max()

7700000.0

Стоимость жилья находится в диапозоне от 75000.0 до 7700000.0

### 3.2 
Какую долю в среднем занимают жилая площадь от всей площади по всем домам?


In [34]:
df [['sqft_living', 'sqft_above']].mean()

sqft_living    2079.899736
sqft_above     1788.396095
dtype: float64

86%

### 3.3 
Как много домов с разными этажами в данных?


In [36]:
df['floors'].nunique()

6

### 3.4 
Насколько хорошие состояния у домов в данных?


In [58]:
df['grade'].value_counts()

7     8981
8     6068
9     2615
6     2038
10    1134
11     399
5      242
12      90
4       29
13      13
3        3
1        1
Name: grade, dtype: int64

### 3.5 
Найдите года, когда построили первый дом, когда построили последний дом в данных?

In [38]:
df.sort_values('yr_built')

id             date     price  bedrooms  bathrooms  \
4697   9126101645  20140610T000000  558000.0         4       2.00   
2961   1947300115  20140619T000000  464000.0         3       1.00   
12369  9138100350  20150218T000000  685000.0         4       2.00   
15016  1703400585  20141215T000000  325000.0         3       2.00   
5236    844000425  20141223T000000  199999.0         3       1.00   
...           ...              ...       ...       ...        ...   
21270  1773100541  20150417T000000  389950.0         3       2.25   
17098  9126100346  20140617T000000  350000.0         3       2.00   
7526   9520900210  20141231T000000  614285.0         5       2.75   
20086  2768100512  20150422T000000  659000.0         2       2.50   
14489  2770601530  20140826T000000  500000.0         2       2.25   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
4697          2180      3870     1.0           0     0  ...      7   
2961          1320      3625     2.0           0     0  ...      7   
12369         2290      6000     1.5           0     3  ...      7   
15016         2330      4950     1.5           0     0  ...      6   
5236           960     10815     1.0           0     0  ...      5   
...            ...       ...     ...         ...   ...  ...    ...   
21270         1580       920     3.0           0     0  ...      8   
17098         1380      3600     3.0           0     0  ...      8   
7526          2730      6401     2.0           0     0  ...      8   
20086         1450      1213     2.0           0     0  ...      9   
14489         1570      1269     2.0           0     0  ...      9   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
4697       1020.0           1160      1900             0    98122  47.6089   
2961       1320.0              0      1900             0    98122  47.6049   
12369      2290.0              0      1900             0    98115  47.6807   
15016      1430.0            900      1900             0    98118  47.5585   
5236        960.0              0      1900             0    98010  47.3091   
...           ...            ...       ...           ...      ...      ...   
21270      1580.0              0      2015             0    98106  47.5578   
17098      1380.0              0      2015             0    98122  47.6074   
7526       2730.0              0      2015             0    98072  47.7685   
20086      1110.0            340      2015             0    98107  47.6692   
14489      1280.0            290      2015             0    98199  47.6514   

          long  sqft_living15  sqft_lot15  
4697  -122.303           1520        2580  
2961  -122.288           1660        5438  
12369 -122.318           2000        3150  
15016 -122.290           1160        5115  
5236  -122.006           1330       10815  
...        ...            ...         ...  
21270 -122.363           1250        1150  
17098 -122.305           1480        3600  
7526  -122.160           2520        6126  
20086 -122.372           1620        1456  
14489 -122.385           1570        6000  

[21613 rows x 21 columns]

In [39]:
df.sort_values('yr_built', ascending=False)

id             date      price  bedrooms  bathrooms  \
21369   923059259  20150401T000000   455950.0         4       2.50   
1763   1832100030  20140625T000000   597326.0         4       4.00   
21262  5694500840  20141125T000000   559000.0         2       3.00   
14215  8156600210  20150326T000000  1285000.0         5       3.50   
20852  1257201420  20140709T000000   595000.0         4       3.25   
...           ...              ...        ...       ...        ...   
8900    917000300  20140520T000000   452000.0         4       1.00   
4438   4232902615  20150428T000000   819000.0         3       1.00   
4397   2767602490  20140724T000000   551000.0         3       1.00   
2566   3037200060  20140926T000000   499000.0         3       2.50   
11266  9827700105  20140917T000000   549000.0         3       2.00   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
21369         2720      5771     2.0           0     0  ...      8   
1763          3570      8250     2.0           0     0  ...     10   
21262         1650       960     3.0           0     0  ...      8   
14215         2980      5100     2.0           0     0  ...     10   
20852         3730      4560     2.0           0     0  ...      9   
...            ...       ...     ...         ...   ...  ...    ...   
8900          1210      3760     1.5           0     0  ...      6   
4438          1300      3600     2.0           0     0  ...      7   
4397           940      1948     1.0           0     0  ...      6   
2566          1750      2150     2.5           0     0  ...      7   
11266         2330      3600     1.5           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
21369      2720.0              0      2015             0    98056  47.4917   
1763       2860.0            710      2015             0    98040  47.5784   
21262      1350.0            300      2015             0    98103  47.6611   
14215      2370.0            610      2015             0    98115  47.6782   
20852      2760.0            970      2015             0    98103  47.6725   
...           ...            ...       ...           ...      ...      ...   
8900       1210.0              0      1900             0    98103  47.6872   
4438       1300.0              0      1900             0    98119  47.6345   
4397        940.0              0      1900             0    98107  47.6733   
2566       1230.0            520      1900          2014    98122  47.6037   
11266      1580.0            750      1900             0    98122  47.6025   

          long  sqft_living15  sqft_lot15  
21369 -122.170           1940        4184  
1763  -122.226           2230       10000  
21262 -122.346           1650        3000  
14215 -122.299           1780        5100  
20852 -122.330           1800        4560  
...        ...            ...         ...  
8900  -122.344           1540        3800  
4438  -122.366           2510        4800  
4397  -122.383           1700        5000  
2566  -122.311           1410        3300  
11266 -122.303           1750        3600  

[21613 rows x 21 columns]

Первый дом постоили в 1900 году последний в 2015

## 4 задача
Ответьте на несколько вопросов

### 4.1 
Сколько в среднем стоят дома, у которых 2 спальни?


In [47]:
df[df['bedrooms'] == 2]['price'].mean()


401372.681884058

### 4.2 
Какая в среднем общая площадь домов, у которых стоимость больше 600 000?


In [48]:
df[df['price'] > 600000]['sqft_above'].mean()

2444.87450039968

### 4.3 
Как много домов коснулся ремонт?


In [57]:
df[df['yr_renovated'] > 0]['id'].count()

914

### 4.4 
Насколько в среднем стоимость домов с оценкой grade домов выше 10 отличается от стоимости домов с оценкой grade меньше 4?

In [63]:
df[df['grade'] > 10]['price'].mean() - df[df['grade'] < 4]['price'].mean()

1488885.1175298805

## 5 задача
Ответьте на несколько вопросов
### 5.1
Выберите дом клиенту
Клиент хочет дом с видом на набережную, как минимум с тремя ванными и с подвалом. Сколько вариантов есть у клиента?


In [68]:
df[(df['waterfront'] > 0) & (df['bathrooms'] >= 3) & (df['sqft_basement'] > 0)]['id'].count()

41

### 5.2 
Выберите дом клиенту
Клиент хочет дом либо с очень красивым видом из окна, либо с видом на набережную, в очень хорошем состоянии и год постройки не меньше 1980 года. В какой ценовом диапазоне будут дома?


In [78]:
house = df[(df['waterfront'] > 0) | (df['waterfront'] == 0) & (df['grade'] == 13) & (df['yr_built'] >= 1980)]
house

id             date      price  bedrooms  bathrooms  \
49      822039084  20150311T000000  1350000.0         3       2.50   
230    8096000060  20150413T000000   655000.0         2       1.75   
246    2025069065  20140929T000000  2400000.0         4       2.50   
264    2123039032  20141027T000000   369900.0         1       0.75   
300    3225069065  20140624T000000  3075000.0         4       5.00   
...           ...              ...        ...       ...        ...   
19984  2025069140  20150317T000000  1898000.0         3       2.50   
20325   518500480  20140811T000000  3000000.0         3       3.50   
20767  8043700105  20150417T000000  2300000.0         4       4.00   
21201   518500460  20141008T000000  2230000.0         3       3.50   
21576  9253900271  20150107T000000  3567000.0         5       4.50   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
49            2753     65005     1.0           1     2  ...      9   
230           1450     15798     2.0           1     4  ...      7   
246           3650      8354     1.0           1     4  ...      9   
264            760     10079     1.0           1     4  ...      5   
300           4550     18641     1.0           1     4  ...     10   
...            ...       ...     ...         ...   ...  ...    ...   
19984         2830      4334     3.0           1     4  ...     10   
20325         4410     10756     2.0           1     4  ...     11   
20767         4360      8175     2.5           1     4  ...     10   
21201         3760      5634     2.0           1     4  ...     11   
21576         4850     10584     2.0           1     4  ...     10   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
49         2165.0            588      1953             0    98070  47.4041   
230        1230.0            220      1915          1978    98166  47.4497   
246        1830.0           1820      2000             0    98074  47.6338   
264         760.0              0      1936             0    98070  47.4683   
300        2600.0           1950      2002             0    98074  47.6053   
...           ...            ...       ...           ...      ...      ...   
19984      2830.0              0      2006             0    98074  47.6318   
20325      3430.0            980      2014             0    98056  47.5283   
20767      3940.0            420      2007             0    98008  47.5724   
21201      2830.0            930      2014             0    98056  47.5285   
21576      3540.0           1310      2007             0    98008  47.5943   

          long  sqft_living15  sqft_lot15  
49    -122.451           2680       72513  
230   -122.375           2030       13193  
246   -122.072           3120       18841  
264   -122.438           1230       14267  
300   -122.077           4550       19508  
...        ...            ...         ...  
19984 -122.071           2830       38211  
20325 -122.205           3550        5634  
20767 -122.104           2670        8525  
21201 -122.205           3560        5762  
21576 -122.110           3470       18270  

[171 rows x 21 columns]

In [74]:
house['price'].max()

7062500.0

In [75]:
house['price'].min()

285000.0

### 5.3 
Выберите дом клиенту
Клиент хочет дом без подвала, с двумя этажами, стоимостью до 150000. Какая оценка по состоянию у таких домов в среднем?

In [80]:
house_1 = df[(df['sqft_basement'] == 0) & (df['floors'] == 2) & (df['price'] <= 150000)]
house_1

id             date     price  bedrooms  bathrooms  \
2589   5061300030  20140508T000000  134000.0         2       1.50   
10105  5466310060  20150324T000000  139500.0         2       1.50   
11255  1843200350  20140722T000000  150000.0         2       1.50   
15610  7614100080  20150211T000000  140000.0         3       1.75   
18332  9272202260  20140924T000000  130000.0         3       1.00   
18939  4239400300  20141129T000000   90000.0         3       1.00   
18988  7399100210  20141126T000000  140000.0         3       1.50   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
2589           980      5000     2.0           0     0  ...      7   
10105         1230      1561     2.0           0     0  ...      7   
11255         1360      1934     2.0           0     0  ...      7   
15610         1270      8991     2.0           0     0  ...      7   
18332         1200      7000     2.0           0     0  ...      7   
18939          980      2490     2.0           0     0  ...      6   
18988         1200      2002     2.0           0     0  ...      8   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
2589        980.0              0      1922          2003    98014  47.7076   
10105      1230.0              0      1983             0    98042  47.3768   
11255      1360.0              0      1978             0    98092  47.2857   
15610      1270.0              0      1981             0    98042  47.3563   
18332      1200.0              0      1908             0    98116  47.5883   
18939       980.0              0      1969             0    98092  47.3170   
18988      1200.0              0      1966             0    98055  47.4659   

          long  sqft_living15  sqft_lot15  
2589  -121.359           1040        5000  
10105 -122.149           1660        2243  
11255 -122.189           1360        1898  
15610 -122.149           1270        8993  
18332 -122.384           3290        6000  
18939 -122.182            980        3154  
18988 -122.189           1270        1848  

[7 rows x 21 columns]

In [81]:
house_1['grade'].mean()

7.0